import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

// Import from fixtures under test
import {
  createOwnedDatabase,
  runPrismaMigrate,
  runPrismaVerify,
  cleanupOwnedResources,
  backupOwnedDatabase,
  restoreOwnedDatabase,
  startOwnedContainer,
  getOwnedContainerReceipt,
  resetSessionStateForTesting,
  createScratchFile,
  cleanScratchFile,
  getOwnedDatabaseUrl,
} from './geolocation-migration.fixtures.js';

const MOCK_VALID_CONTAINER_ID = 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0';

describe('Geolocation Migration Fixtures Unit & Safety Contract (Mocked / No Docker)', () => {
  let tempDir: string;
  let fakeBinDir: string;
  let logFile: string;
  let tokenFile: string;
  let originalPath: string;

  beforeEach(() => {
    resetSessionStateForTesting();

    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'geo-fixtures-spec-'));
    fakeBinDir = path.join(tempDir, 'bin');
    fs.mkdirSync(fakeBinDir, { recursive: true });
    logFile = path.join(tempDir, 'calls.log');
    tokenFile = path.join(tempDir, 'token.txt');
    fs.writeFileSync(logFile, '');

    originalPath = process.env.PATH ?? '';
    process.env.PATH = `${fakeBinDir}:${originalPath}`;
  });

  afterEach(() => {
    process.env.PATH = originalPath;
    resetSessionStateForTesting();
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch {
      // ignore
    }
  });

  function createFakeExecutable(name: string, scriptContent: string) {
    const filePath = path.join(fakeBinDir, name);
    fs.writeFileSync(filePath, `#!/usr/bin/env bash\n${scriptContent}\n`, { mode: 0o755 });
    return filePath;
  }

  function setupFakeDocker(options?: {
    inspectToken?: string;
    initLogSeen?: boolean;
    failRun?: boolean;
    containerId?: string;
    failPort?: boolean;
  }) {
    const inspectTokenOverride = options?.inspectToken ? `"${options.inspectToken}"` : '""';
    const initLog = options?.initLogSeen !== false
      ? 'PostgreSQL init process complete; ready for start up.'
      : 'Initial log output without readiness milestone';
    const cid = options?.containerId ?? MOCK_VALID_CONTAINER_ID;
    const failRun = options?.failRun ? 'exit 1' : `echo "${cid}"\nexit 0`;
    const portAction = options?.failPort ? 'exit 1' : 'echo "127.0.0.1:54999"\nexit 0';

    createFakeExecutable(
      'docker',
      `
echo "docker $@" >> "${logFile}"
if [ "$1" = "run" ] || [ "$1" = "create" ]; then
  for arg in "$@"; do
    if [[ "$arg" == geo-owner-token=* ]]; then
      echo "\${arg#geo-owner-token=}" > "${tokenFile}"
    fi
  done
  ${failRun}
elif [ "$1" = "port" ]; then
  ${portAction}
elif [ "$1" = "logs" ]; then
  echo "${initLog}"
  exit 0
elif [ "$1" = "inspect" ]; then
  if [ -n ${inspectTokenOverride} ]; then
    echo ${inspectTokenOverride}
  elif [ -f "${tokenFile}" ]; then
    cat "${tokenFile}"
  else
    echo "unknown-token"
  fi
  exit 0
elif [ "$1" = "exec" ]; then
  echo "1"
  exit 0
elif [ "$1" = "rm" ]; then
  exit 0
fi
exit 0
`,
    );

    createFakeExecutable(
      'pnpm',
      `
echo "pnpm $@" >> "${logFile}"
exit 0
`,
    );
  }

  describe('Refusal of External and Unregistered Database URLs', () => {
    it('refuses external or shared DATABASE_URL in Prisma migrate helper', () => {
      setupFakeDocker();
      expect(() => {
        runPrismaMigrate('postgresql://logistica_user:logistica_password123@localhost:5432/logistica_db');
      }).toThrow(/Refusing operation on unregistered \/ external database URL/i);
    });

    it('refuses external database URL in Prisma verify helper', () => {
      setupFakeDocker();
      expect(() => {
        runPrismaVerify('postgresql://logistica_user:logistica_password123@localhost:5432/logistica_db');
      }).toThrow(/Refusing operation on unregistered \/ external database URL/i);
    });

    it('accepts registered database URL generated by the owned session', () => {
      setupFakeDocker();
      const receipt = startOwnedContainer({ readinessTimeoutMs: 1000 });
      expect(receipt).toBeDefined();
      expect(fs.readFileSync(logFile, 'utf-8')).toContain('run -d --rm --pull=never');
      const dbUrl = createOwnedDatabase('geo_registered_test_db');
      expect(typeof dbUrl).toBe('string');

      // Valid registered URL must not throw
      expect(() => {
        runPrismaMigrate(dbUrl);
      }).not.toThrow();
    });

    it('does not register URL when merely calling getOwnedDatabaseUrl without creation', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      const uncreatedUrl = getOwnedDatabaseUrl('geo_uncreated_db');
      expect(() => {
        runPrismaMigrate(uncreatedUrl);
      }).toThrow(/Refusing operation on unregistered \/ external database URL/i);
    });

    it('rejects query string variants of registered URLs', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      const dbUrl = createOwnedDatabase('geo_query_test_db');
      const urlWithQuery = `${dbUrl}?schema=public`;
      expect(() => {
        runPrismaMigrate(urlWithQuery);
      }).toThrow(/Refusing operation on unregistered \/ external database URL/i);
    });
  });

  describe('Creation Safety & Prohibition of Pre-Deletion', () => {
    it('never executes DROP DATABASE or pg_terminate_backend during database creation', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      fs.writeFileSync(logFile, ''); // reset log

      createOwnedDatabase('geo_clean_create_db');
      const logContent = fs.readFileSync(logFile, 'utf8');

      // Must execute CREATE DATABASE without prior DROP or pg_terminate
      expect(logContent).toContain('CREATE DATABASE');
      expect(logContent).not.toMatch(/DROP\s+DATABASE/i);
      expect(logContent).not.toMatch(/pg_terminate_backend/i);
    });

    it('never deletes fixed or shared containers like logistica_postgres during cleanup', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      fs.writeFileSync(logFile, ''); // reset log

      cleanupOwnedResources();
      const logContent = fs.readFileSync(logFile, 'utf8');

      expect(logContent).not.toContain('logistica_postgres');
    });
  });

  describe('Receipt Tracking & Container Lifecycle Validation', () => {
    it('validates container ID as full 64 hex and refuses non-hex ID without docker rm', () => {
      setupFakeDocker({ containerId: 'short-invalid-id' });
      fs.writeFileSync(logFile, '');

      expect(() => {
        startOwnedContainer({ readinessTimeoutMs: 500 });
      }).toThrow(/Invalid container ID format/i);

      const logContent = fs.readFileSync(logFile, 'utf8');
      expect(logContent).not.toMatch(/rm\s+-f/);
    });

    it('verifies ownership label before docker rm on port failure and removes if matching', () => {
      setupFakeDocker({ failPort: true });
      fs.writeFileSync(logFile, '');

      expect(() => {
        startOwnedContainer({ readinessTimeoutMs: 500 });
      }).toThrow();

      const logContent = fs.readFileSync(logFile, 'utf8');
      expect(logContent).toContain('inspect');
      expect(logContent).toContain(`rm -f ${MOCK_VALID_CONTAINER_ID}`);
    });

    it('refuses docker rm on port failure if inspect token does not match session', () => {
      setupFakeDocker({ failPort: true, inspectToken: 'foreign-token' });
      fs.writeFileSync(logFile, '');

      expect(() => {
        startOwnedContainer({ readinessTimeoutMs: 500 });
      }).toThrow();

      const logContent = fs.readFileSync(logFile, 'utf8');
      expect(logContent).toContain('inspect');
      expect(logContent).not.toMatch(/rm\s+-f/);
    });

    it('refuses to delete a container if inspect label does not match session owner token during cleanup', () => {
      setupFakeDocker({ inspectToken: 'foreign-unknown-owner-token' });
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      fs.writeFileSync(logFile, '');

      expect(() => {
        cleanupOwnedResources();
      }).toThrow(/Refusing to delete unowned or foreign container/i);

      const logContent = fs.readFileSync(logFile, 'utf8');
      expect(logContent).not.toMatch(/rm\s+-f/);
    });

    it('returns an immutable frozen receipt copy and resists external tampering', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      const receipt = getOwnedContainerReceipt();
      expect(receipt).not.toBeNull();
      expect(Object.isFrozen(receipt)).toBe(true);

      expect(() => {
        // @ts-expect-error test runtime mutation
        receipt.containerId = 'tampered-container-id';
      }).toThrow();
    });

    it('rejects malformed non-UUID sessionToken in start options without invoking docker', () => {
      setupFakeDocker();
      fs.writeFileSync(logFile, '');

      expect(() => {
        startOwnedContainer({ sessionToken: 'malicious-prefix; rm -rf /' });
      }).toThrow(/Invalid sessionToken format: must be strict UUID/i);

      const logContent = fs.readFileSync(logFile, 'utf8');
      expect(logContent).toBe('');
    });
  });

  describe('Scratch Boundary, Backup Containment & Symlink Refusal', () => {
    it('creates scratch file strictly inside owned scratchDir with private 0600 mode', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      const scratchFile = createScratchFile('valid-prefix');

      expect(fs.existsSync(scratchFile)).toBe(true);
      const stat = fs.statSync(scratchFile);
      expect(stat.mode & 0o777).toBe(0o600);
      expect(path.basename(scratchFile)).toMatch(/^valid-prefix-[a-f0-9]{8}\.sql$/);
    });

    it('rejects malicious prefix in createScratchFile', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });

      const maliciousPrefixes = ['../escape', '/abs/path', 'bad/slash', 'invalid space', ''];
      for (const prefix of maliciousPrefixes) {
        expect(() => {
          createScratchFile(prefix);
        }).toThrow(/Invalid scratch prefix/i);
      }
    });

    it('refuses backup to foreign or unregistered path', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      createOwnedDatabase('geo_boundary_test_db');

      const foreignFile = path.join(tempDir, 'foreign.sql');
      expect(() => {
        backupOwnedDatabase('geo_boundary_test_db', foreignFile);
      }).toThrow(/Refusing backup to unregistered or uncontained scratch path/i);

      expect(fs.existsSync(foreignFile)).toBe(false);
    });

    it('refuses restore from foreign or unregistered path', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      createOwnedDatabase('geo_boundary_test_db');

      const foreignFile = path.join(tempDir, 'foreign_source.sql');
      fs.writeFileSync(foreignFile, '-- foreign', { mode: 0o600 });

      expect(() => {
        restoreOwnedDatabase('geo_boundary_test_db', foreignFile);
      }).toThrow(/Refusing restore from unregistered or uncontained scratch path/i);
    });

    it('refuses cleanScratchFile on unregistered or foreign path', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });

      const foreignFile = path.join(tempDir, 'keep_me.sql');
      fs.writeFileSync(foreignFile, '-- important', { mode: 0o600 });

      expect(() => {
        cleanScratchFile(foreignFile);
      }).toThrow(/Refusing cleanup of unregistered or uncontained path/i);

      expect(fs.existsSync(foreignFile)).toBe(true);
    });

    it('refuses symlinks in backup, restore and clean operations', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      createOwnedDatabase('geo_boundary_test_db');

      const legitTarget = createScratchFile('target');
      const outsideSecret = path.join(tempDir, 'secret.txt');
      fs.writeFileSync(outsideSecret, 'secret', { mode: 0o600 });
      // Replace registered file with symlink pointing outside
      fs.unlinkSync(legitTarget);
      fs.symlinkSync(outsideSecret, legitTarget);

      expect(() => {
        backupOwnedDatabase('geo_boundary_test_db', legitTarget);
      }).toThrow(/Refusing backup to symlink or foreign path/i);

      expect(() => {
        restoreOwnedDatabase('geo_boundary_test_db', legitTarget);
      }).toThrow(/Refusing restore from symlink or foreign path/i);

      expect(() => {
        cleanScratchFile(legitTarget);
      }).toThrow(/Refusing cleanup of symlink or uncontained path/i);
    });

    it('executes legitimate end-to-end backup, restore and cleanup workflow via registered scratch', () => {
      setupFakeDocker();
      startOwnedContainer({ readinessTimeoutMs: 1000 });
      createOwnedDatabase('geo_boundary_test_db');

      const scratchPath = createScratchFile('legit-flow');
      expect(() => {
        backupOwnedDatabase('geo_boundary_test_db', scratchPath);
      }).not.toThrow();

      expect(() => {
        restoreOwnedDatabase('geo_boundary_test_db', scratchPath);
      }).not.toThrow();

      expect(fs.existsSync(scratchPath)).toBe(true);
      cleanScratchFile(scratchPath);
      expect(fs.existsSync(scratchPath)).toBe(false);
    });
  });

  describe('Readiness Contract', () => {
    it('fails readiness if container does not emit post-initialization milestone', () => {
      setupFakeDocker({ initLogSeen: false });

      expect(() => {
        startOwnedContainer({ readinessTimeoutMs: 250 });
      }).toThrow(/Readiness check failed/i);
    });
  });
});
