services:
  postgres:
    image: postgres:16-alpine
    container_name: logistica_postgres
    restart: always
    environment:
      POSTGRES_USER: logistica_user
      POSTGRES_PASSWORD: logistica_password123
      POSTGRES_DB: logistica_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U practicas"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
